### ISSUE TITLE
not actual Headers  getting added passed but ainstead of that array index.

### ISSUE THREAD

**Issue by shekharramola** [alhazmy13/angular5-csv#3]
options = {
    fieldSeparator: ",",
    quoteStrings: '"',
    decimalseparator: ".",
    showLabels: true,
    showTitle: true,
    headers: ["First Name", "Last Name", "ID"]
  };
   new Angular5Csv(this.data, "My Report", this.options);

    this.data = [
      {
        name: "Test 1",
        age: 13,
        average: 8.2,
        approved: true,
        description: "using 'Content here, content here' "
      },
      {
        name: "Test 2",
        age: 11,
        average: 8.2,
        approved: true,
        description: "using 'Content here, content here' "
      },
      {
        name: "Test 4",
        age: 10,
        average: 8.2,
        approved: true,
        description: "using 'Content here, content here' "
      }
    ];

CSV will be like

My Report

0,1,2
"Test 1",13,8.2,TRUE,"using 'Content here, content here' "
"Test 2",11,8.2,TRUE,"using 'Content here, content here' "
"Test 4",10,8.2,TRUE,"using 'Content here, content here' "

**Comment by DawidvanGraan** [comment]
I'm also seeing this on `v0.2.7`.

**Comment by abhisgit** [comment]
See pull request https://github.com/alhazmy13/angular5-csv/pull/2
This has been merged and it should work fine now.

**Comment by alhazmy13** [comment]
Can you please test it with version `v0.2.8`?
