### ISSUE TITLE
Need it on button click 

### ISSUE THREAD

**Issue by Anujmoglix** [alhazmy13/angular5-csv#5]
Hi ,
  I want to download grid data as csv on click of button like  :- 
 ```
 public downloadCsv() {
        //new Angular5Csv(this.data, 'My Report');
    }
```
Now tell me how to do this bez it is giving issue on new keyword. [**unused expression, expected an assignment or function call (no-unused-expression)**]

**Comment by VlnRbn** [comment]
`
    onexport(){

      let dataArray: Array<any> = [
        { date: "21-2-2017", successfulTask: '10', cancelledTask: '5'},
        { date: "1-2-2017", successfulTask: '2', cancelledTask: '7'},
      ]

        var options = {}
        if (dataArray.length !=0){
          options = { 
          fieldSeparator: ',',
          quoteStrings: '"',
          decimalseparator: '.',
          showLabels: true, 
          showTitle: true,
          useBom: true,
          headers: Object.keys(dataArray[0])
        };
      }
        new Angular5Csv(dataArray,'Report', options);
      }
}
`

**Comment by Anujmoglix** [comment]
Got the issue . Project was working fine but i was showing warning and on Git push i was not able to push code . Workaround was 
`this.MYfile = new Angular5Csv(this.data, 'Report', options);`
Define any variable then it was working properly
