### ISSUE TITLE
 TS7016

### ISSUE THREAD

**Issue by skuzmin** [alhazmy13/angular5-csv#6]
Hi,

I have faced with next error:
TS7016: Could not find a declaration file for module 'angular5-csv/Angular5-csv'.

Could you add declaration in d.ts file ?

Thank you!

**Comment by alhazmy13** [comment]
Hi @skuzmin 
Can you please update your `tsconfig.json` with  `"noImplicitAny": false`

**Comment by alhazmy13** [comment]
FYI, there's no need to import `Angular5-csv` in your module, just import it in your component 
`import { Angular5Csv } from 'angular5-csv/Angular5-csv';`

**Comment by derreck503** [comment]
@skuzmin

import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';

Solved it for me!

**Comment by KrishnaAnanthi** [comment]
Please update the import statement in https://www.npmjs.com/package/angular5-csv
