### ISSUE TITLE
Getting "My Report" in File

### ISSUE THREAD

**Issue by Anujmoglix** [alhazmy13/angular5-csv#7]
Hi , 
 I am  Getting "My Report" on file which is downloading but it is not anywhere .I want to remove that and add some other part which will come dynamically from Api . 
 From Where i Can do this ?

**Comment by alhazmy13** [comment]
Hi @Anujmoglix 
You can update the title `My Report` from `new Angular5Csv(data, 'YOUR_TITLE');`

If you want to hide it, then play with this options and pass it to `Angular5Csv` constructor 

```js
  var options = { 
    fieldSeparator: ',',
    quoteStrings: '"',
    decimalseparator: '.',
    showLabels: true, 
    showTitle: true,
    useBom: true,
    noDownload: true,
    headers: ["First Name", "Last Name", "ID"]
  };

  Angular5Csv(data, filename, options);
```

**Comment by Anujmoglix** [comment]
Thanks.I will check in a while .Can you help me to get the result like this ?
![selection_106](https://user-images.githubusercontent.com/26056096/38581064-512f215e-3d29-11e8-99a7-9a376ecdf8ed.png)

**Comment by alhazmy13** [comment]
You can add your header is a title and then pass it to option settings, for ex:

```js
let data = [
            {
                value1: "Test 1",
                value2: 13,
                value3: 8.2,
            },
            {
                value1: "Test 2",
                value2: 13,
                value3: 8.2,
            }
        ];
        let title = "Header1 \r\n\n" +
            "Header2 \r\n\n" +
            "Header3 \r\n\n" +
            "Header4 \t\t Another Column";


        let options = {
            fieldSeparator: '\t',
            showLabels: true,
            showTitle: true,
            title: title,
            headers: ["Column Header1", "Column Header2","Column Header3"]
        };

       new Angular5Csv(data, "file", options);
```

Since you wanna to open this file with excel, then you need to update `fieldSeparator` with `\t`

**Comment by Anujmoglix** [comment]
oh .wow . This is perfect what i want . One more query is that , Is it possible to merge cells here ? like in my screenshot (previous image ) we merged cell of A,B,C,D,E,F .

**Comment by alhazmy13** [comment]
This isn't possible with CSV files.

CSV means comma-separated values (CSV), file stores tabular data (numbers and text) in plain text (It is just data, with no attached formatting).
If this important to you then you need to search for any library that generates an excel file.
